In [1]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [8]:
import seaborn as sns

In [31]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
#df['target'] = data.target
df['species'] = pd.Categorical.from_codes(data.target, data.target_names)

In [21]:
rows, cols = df.shape
print("Rows:" , rows)
print("colums:" , cols)

Rows: 150
colums: 6

In [37]:
y=df["species"]
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [40]:
x=df.drop("species" , axis=1)
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [41]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [43]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42, stratify=y
)

In [45]:
x_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3
..                 ...               ...                ...               ...
37                 4.9               3.6                1.4               0.1
79                 5.7               2.6                3.5               1.0
33                 5.5               4.2                1.4               0.2
94                 5.6               2.7                4.2               1.3
3                  4.6               3.1                1.5               0.2

[105 rows x 4 columns]

In [50]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)   # create the model
knn.fit(x_train, y_train)                   # train the model

KNeighborsClassifier(n_neighbors=3)

In [51]:
knn5 = KNeighborsClassifier(n_neighbors=3)
knn5.fit(x_train, y_train)
accuracy = knn5.score(x_test, y_test)
print("Accuracy with 3 neighbors:", accuracy)

Accuracy with 3 neighbors: 0.9555555555555556

In [54]:
y_pred = knn.predict(x_test)
print(y_pred)

['virginica' 'versicolor' 'versicolor' 'versicolor' 'virginica'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'virginica' 'setosa'
 'setosa' 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'versicolor' 'setosa' 'versicolor' 'virginica'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'setosa'
 'virginica' 'virginica' 'versicolor' 'setosa' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor']

In [55]:
x_test.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
107                7.3               2.9                6.3               1.8
63                 6.1               2.9                4.7               1.4
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6
127                6.1               3.0                4.9               1.8

In [68]:
newdata = pd.DataFrame({
    "sepal length (cm)": [0.2],
    "sepal width (cm)": [1.5],
    "petal length (cm)": [2.2],
    "petal width (cm)": [0.6]
})
prediction= knn.predict(newdata)
prediction[0]

'setosa'

In [69]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)